# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Library tests

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          - library: numpy
            version: 1.21.6
            python-version: '3.10'
          - library: numpy
            version: 1.22.4
            python-version: '3.10'

          - library: scikit-learn
            version: 0.24.2
            python-version: 3.9
          - library: scikit-learn
            version: 1.0.2
            python-version: '3.10'

          - library: scipy
            version: 1.7.3
            python-version: '3.10'
          - library: scipy
            version: 1.8.1
            python-version: '3.10'

          - library: crlibm
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .

    - name: Pre-install numpy
      if: ${{ matrix.library == 'numpy' }}
      run: |
        python -m pip install numpy==${{ matrix.version }}

    - name: Pre-install scikit-learn
      if: ${{ matrix.library == 'scikit-learn' }}
      run: |
        python -m pip install scikit-learn==${{ matrix.version }}

    - name: Pre-install scipy
      if: ${{ matrix.library == 'scipy' }}
      run: |
        python -m pip install scipy==${{ matrix.version }}

    - name: Pre-install crlibm
      if: ${{ matrix.library == 'crlibm' }}
      run: |
        python -m pip install crlibm

    - name: List installed packages
      run: |
        python -m pip list
    - name: Test with pytest
      run: |
        pytest
