# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Library tests

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          - library: numpy
            version: 2.0.2
            python-version: '3.11'
          - library: numpy
            version: 2.1.3
            python-version: '3.11'

          - library: scikit-learn
            version: 1.4.2
            python-version: '3.11'
          - library: scikit-learn
            version: 1.5.2
            python-version: '3.12'

          - library: scipy
            version: 1.13.1
            python-version: '3.11'
          - library: scipy
            version: 1.14.1
            python-version: '3.11'

          - library: crlibm
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install .

    - name: Pre-install numpy
      if: ${{ matrix.library == 'numpy' }}
      run: |
        python -m pip install numpy==${{ matrix.version }}

    - name: Pre-install scikit-learn
      if: ${{ matrix.library == 'scikit-learn' }}
      run: |
        python -m pip install scikit-learn==${{ matrix.version }}

    - name: Pre-install scipy
      if: ${{ matrix.library == 'scipy' }}
      run: |
        python -m pip install scipy==${{ matrix.version }}

    - name: Pre-install crlibm
      if: ${{ matrix.library == 'crlibm' }}
      run: |
        python -m pip install setuptools==60.2.0 wheel==0.37.1
        python -m pip install crlibm

    - name: List installed packages
      run: |
        python -m pip list
    - name: Test with pytest
      run: |
        pytest
