# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Numpy tests

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:
          - name: Numpy 1.19.5 (Python 3.8)
            python-version: 3.8
            numpy-version: 1.19.5
          - name: Numpy 1.20.3 (Python 3.9)
            python-version: 3.9
            numpy-version: 1.20.3
          - name: Numpy 1.21.2 (Python 3.9)
            python-version: 3.9
            numpy-version: 1.21.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest
